### ISSUE TITLE
Gen: Supports request params

### ISSUE THREAD

**Issue by vnhdx** [ez-connect/go-rest#14]
Allows define params in `settings.yml`

```yml
parameters:
  - name: productId
    in: path
    type: string
    required: true
  - name: q
    in: query
    type: string
  - name: payload
    type: PayloadModel
    in: body
```
