### ISSUE TITLE
Supports more validations

### ISSUE THREAD

**Issue by vnhdx** [ez-connect/go-rest#19]

**Comment by vnhdx** [comment]
```yml
      - name: name
        type: string
        validate: "required"
      - name: originalPrice
        type: float64
        allowsEmpty: true
        validate: "max=1000000000000,min=0"
```
